sudo: required
services:
  - docker

before_install:
  - docker build  -t amarmodi1784/docker-react -f Dockerfile.dev .

  #All commands to run testsuite
script:
  - docker run amarmodi1784/docker-react npm run test -- --coverage