sudo: required
services:
  - docker

before_install:
  - docker build  -t amarmodi1784/docker-react -f Dockerfile.dev .

  #All commands to run testsuite
script:
  - docker run amarmodi1784/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-initial"
  env: "DockerInitial-env"
  bucket_name: "elasticbeanstalk-us-east-2-128525079941"
  bucket_path: "docker-initial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"